simcard0000/se-webring

index.html
se-webring.css

Adds footer with a different style

Add footer

---

js/se-webring.js

**Full Name:** Will Harris
**Full website URL:** https://willharris.ca
**LinkedIn or a similar profile:** https://github.com/fjij

add site: willharris.ca

---

js/se-webring.js

**Full Name:** Anthony Wang
**Full website URL:** https://anthonywang.dev
**LinkedIn or a similar profile:** https://github.com/anthonyftwang/

add site: anthonywang.dev

---

js/se-webring.js

**Full Name:** Kelvin Zhang
**Full website URL:** https://kelvinzhang.ca/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/kelvin-zhang/

Add kelvinzhang.ca

---

js/se-webring.js

**Full Name:** Zuomiao Hu
**Cohort Year:**  2024
**Full website URL:** https://zonahu.tech/
**LinkedIn or a similar profile:**  https://www.linkedin.com/in/zonahu/

add site: zonahu.tech

---

js/se-webring.js

**Full Name:** Yash Arora
**Full website URL:** https://yasharora.com
**LinkedIn or a similar profile:** [LinkedIn](https://www.linkedin.com/in/yasharora0606/)

Add site: Yash Arora

---

js/se-webring.js

**Full Name:** Damian Reiter
**Cohort Year:** 2023
**Full website URL:** https://damian.bio/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/damianreiter/

add site: Damian Reiter

---

js/se-webring.js

**Full Name:** Jonathan Xu
**Full website URL:** https://jonathanxu.com/
**LinkedIn or a similar profile:** [Linkedin](https://www.linkedin.com/in/jonathanxu01/)

Add site: Jonathan Xu

---

js/se-webring.js

**Full Name:** Hannah Guo
**Full website URL:**  https://hannahguo.me/
**LinkedIn or a similar profile:**  https://www.linkedin.com/in/hannah-guo/

adding hannahguo

---

js/se-webring.js

**Full Name:** Mufeez Amjad
**Cohort Year:** 2023
**Full website URL:** https://mufeez.me
**LinkedIn or a similar profile:** linkedin.com/in/mufeez-amjad

Add mufeez.me

---

js/se-webring.js

**Full Name:** \Yifei Zhang
**Cohort Year:** \2023
**Full website URL:** \https://yifeiz.com
**LinkedIn or a similar profile:** \https://www.linkedin.com/in/yifei-zhang1/

add site:yifeiz.com

---

js/se-webring.js

**Full Name:** Elena Pan
**Full website URL:** https://elena-pan.github.io/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/elena-pan/

Add site: Elena Pan

---

js/se-webring.js

**Full Name:** Ryan Deng
**Full website URL:** https://www.ryandeng.me/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/ryandeng32/

Add site: Ryan Deng

---

js/se-webring.js

**Full Name:**  Dylan Snelgrove
**Cohort Year:**  3B (2024)
**Full website URL:** https://dylansnelgrove.com
**LinkedIn or a similar profile:**  https://www.linkedin.com/in/dylan-snelgrove

Add dylan's website

---

js/se-webring.js

**Full Name:** Jason Zhou
**Full website URL:** https://zhoujas.github.io/personal/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/zhoujas/

add site: Jason Zhou

---

js/se-webring.js

**Full Name:** Jack Douglas
**Full website URL:** https://jackdouglas.tech/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/j-douglas/

Add site: Jack Douglas

---

js/se-webring.js

**Full Name:** Evan Zhang
**Full website URL:** https://evanzhang.ca
**LinkedIn or a similar profile:** https://linkedin.com/in/ninjaclasher

Add site: Evan Zhang

---

js/se-webring.js

**Full Name:** Justin Lin
**Full website URL:** https://justin-lin.com
**LinkedIn or a similar profile:** https://www.linkedin.com/in/justin-lin-905/

Add site: Justin Lin

---

js/se-webring.js

**Full Name:** Donghwui Kim
**Full website URL:** www.donghwui.com
**LinkedIn or a similar profile:** https://www.linkedin.com/in/donghwui/

Add Site: Donghwui Kim

---

js/se-webring.js

**Full Name:** Rajan Agarwal
**Full website URL:**  [https://rajan.sh](https://rajan.sh)
**LinkedIn or a similar profile:** https://www.linkedin.com/in/rajansagarwal

Add Site: Rajan Agarwal

---

js/se-webring.js

**Full Name:** Krish Shah
**Cohort Year:** 2026
**Full website URL:** https://krishkrosh.com
**LinkedIn or a similar profile:** https://twitter.com/krishrshah

Add site: Krish Shah

---

js/se-webring.js

**Full Name:** Jasmine Tai
**Full website URL:** https://www.jtai.ca/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/jasmine-tai-85b0b6221/

Add site: Jasmine Tai

---

js/se-webring.js

**Full Name:** Alex Zhu
**Full website URL:** https://probablyalexzhu.github.io
**LinkedIn or a similar profile:** https://www.linkedin.com/in/probablyalexzhu

 Add site: Alex Zhu

---

js/se-webring.js

**Full Name:** Patrick Gu
**Full website URL:** https://patrickgu.ca/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/patrickgu-/

Add site: Patrick Gu

---

js/se-webring.js

To add your site to the webring, you must be a current student or an alum of the undergraduate Software Engineering program at the University of Waterloo (Waterloo, ON, Canada). 
Full Name: Ian Korovinsky
Cohort Year: 2028 
Full website URL: https://iankorovinsky.github.io/
So we know you're human: LinkedIn or a similar profile: https://www.linkedin.com/in/ian-korovinsky/
Don't forget to also add your entry to the end of the allSites array in the se-webring.js file (name, year, personal website), and to add the add site label to your pull request.

Add Site: Ian Korovinsky

---

js/se-webring.js

**Full Name:** Rajat Patwari
**Full website URL:** https://rajatpatwari.com
**LinkedIn or a similar profile:** https://www.linkedin.com/in/patwarir

Add Site: Rajat Patwari

---

js/se-webring.js

**Full Name:** Jomills Jose Anand
**Cohort Year:** 2026
**Full website URL:** https://jomills.notion.site
**LinkedIn or a similar profile:** https://www.linkedin.com/in/jomillsjoseanand

Add website: Jomills Jose Anand

---

js/se-webring.js

**Full Name:** \<insert full name here>
**Cohort Year:** \<insert cohort year here (the year of expected graduation)>
**Full website URL:** \<insert full website URL here>
**LinkedIn or a similar profile:** \<insert other profile URL here>

Update Bilal Khan url

---

js/se-webring.js

**Full Name:** Pearl Natalia
**Full website URL:** https://www.pearlnatalia.com
**LinkedIn or a similar profile:** https://linkedin.com/in/pearlnatalia

Adding Pearl Natalia's website to se-webring.js

---

js/se-webring.js

**Full Name:** Ishaan Dey
**Full website URL:** https://www.ishaand.com
**LinkedIn or a similar profile:** https://www.linkedin.com/in/ishaan1013
_Don't forget to also add your entry to the end of the_ `allSites` _array in the_ `se-webring.js` _file (name, year, personal website)!_

Add site: Ishaan Dey

---

README.md

For posterity, and testing the updated GitHub actions!

Update README.md - sites.js

---

js/sites.js

**Full Name:**  Chris Fang
**Cohort Year:**  2025
**Full website URL:**  https://www.chrisfang.dev/
**LinkedIn or a similar profile:**  https://www.linkedin.com/in/chr1sf4ng/

Add site: Chris Fang

---

js/sites.js

**Full Name:** \<Stevem Yang>
**Cohort Year:** \<2028>
**Full website URL:** \<https://www.yangsteven.com/>
**LinkedIn or a similar profile:** \<https://www.linkedin.com/in/stevenyangtan/>

steven yang

---

js/sites.js

**Full Name:** Darsh Shah
**Full website URL:** https://darshshah.ca
**LinkedIn or a similar profile:** https://www.linkedin.com/in/dshah108/

Add Darsh Shah

---

js/sites.js

**Full Name:** \Wilson Chen
**Cohort Year:** \2028
**Full website URL:** \https://wilsonchenn.com
**LinkedIn or a similar profile:** \https://www.linkedin.com/in/wilson-chen-/

Added my name on sites.js

---

js/sites.js

**Full Name:** \Aurora Shi
**Cohort Year:** \2028
**Full website URL:** \https://aurorashi.live/
**LinkedIn or a similar profile:** \https://www.linkedin.com/in/aurora-shi-387656247/

added aurora shi's website

---

js/sites.js

**Full Name:** \Aarjav Patni
**Cohort Year:** \2028
**Full website URL:** \https://aarjavpatni.me
**LinkedIn or a similar profile:** \https://linkedin.com/in/aarjavpatni/

Add Aarjav's site

---

js/sites.js

**Full Name:** Abhinav Balasubramanian
**Cohort Year:**2027
**Full website URL:** https://abhinav-bala.github.io/portfolio/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/abhinavbala24/

added abhinav's website

---

js/sites.js

**Full Name:** Lucas Kim
**Full website URL:** https://lucaskamadakim.com/
_So we know you're human:_ I am human
**LinkedIn or a similar profile:** https://www.linkedin.com/in/lucaskim65/

Add Lucas Kim's website

---

.github/pull_request_template.md
js/sites.js

**Full Name:** Alice Zhao
**Full website URL:** http://aliicezhao.com/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/aliicezhao/

Adding Website

---

js/sites.js

**Full Name:** Jack Douglas
**Cohort Year:**  Class of 2024
**Full website URL:** j-douglas.github.io
_So we know you're human:_ :)

Updating Jack Douglas domain

---

js/sites.js

**Full Name:** Paul Lee
**Full website URL:** https://paullee.dev/
_So we know you're human:_ i am robot
**LinkedIn or a similar profile:** https://www.linkedin.com/in/paul-lee-dev/

add paullee.dev

---

js/sites.js

**Full Name:** Adam Chen
**Full website URL:** https://encodeous.ca
_So we know you're human:_ I'm not a bot, trust :)
**LinkedIn or a similar profile:** https://www.linkedin.com/in/adamjiaqichen/
Thanks!

Add Website

---

js/sites.js

**Full Name:** Naman Biyani
**Full website URL:** https://www.namanbiyani.com
_So we know you're human:_ 
**LinkedIn or a similar profile:** https://www.linkedin.com/in/naman-biyani-361b96233/

Update sites.js with namanbiyani.com

---

js/sites.js

**Full Name:** Balaji Leninrajan
**Full website URL:** https://balajileninrajan.github.io/homepage/
_So we know you're human:_I am very human, for better and for worse
**LinkedIn or a similar profile:** https://www.linkedin.com/in/balaji-leninrajan/

added website

---

js/sites.js

**Full Name:** Patrick Huang
**Full website URL:** https://www.patrickhuang.co/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/patrick-y-huang/

Add Patrick website

---

js/sites.js

**Full Name:** Ian Korovinsky
**Cohort Year:**  2028
**Full website URL:**  https://iankorovinsky.ca
**LinkedIn or a similar profile:**  https://www.linkedin.com/in/ian-korovinsky/

Update Ian Website

---

js/sites.js

**Full Name:** Krish Shah
**Full website URL:** https://shahkrish.ca/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/kri-shah

added details

---

js/sites.js

**Full Name:** Sumedh Dhanvanthry
**Full website URL:**  https://www.sumedh.ca/
**LinkedIn or a similar profile:** (https://www.linkedin.com/in/sumedh-dhanvanthry/)

added sumedh site

---

js/sites.js

**Full Name:** Adam Selim
**Full website URL:** https://adamselim.com
**LinkedIn or a similar profile:** https://www.linkedin.com/in/adamzselim/

Add Adam site

---

js/sites.js

**Full Name:** Martin Baldwin
**Full website URL:** https://marbal.ca
**LinkedIn or a similar profile:** https://linkedin.com/in/martin-baldwin

Add Martin website

---

js/sites.js

**Full Name:** Nuthanan Tharmarajah
**Full website URL:** https://nuthanan.com/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/nuthanan-tharmarajah/

Add Nuthanan's website

---

js/sites.js

**Full Name:** Lindsay Zhang
**Full website URL:** https://itslinds.dev
**LinkedIn or a similar profile:** https://www.linkedin.com/in/lindzhang/

Lindsay's personal website

---

js/sites.js

**Full Name:** \Honzik Schenk
**Cohort Year:** \2029
**Full website URL:** \https://honzikschenk.me/
**LinkedIn or a similar profile:** \https://www.linkedin.com/in/honzik-schenk/

Add Honzik Schenk to the list of sites

---

js/sites.js

**Full Name:** \<Finn Cullen>
**Cohort Year:** \<2029>
**Full website URL:** \<https://fatcullen.github.io/>
**LinkedIn or a similar profile:** \<https://www.linkedin.com/in/finn-cullen-a6a012346/>

Added Finn Cullen

---

js/sites.js

**Full Name:** \<Finn Cullen>
**Cohort Year:** \<2029>
**Full website URL:** \<https://fatcullen.me/>
**LinkedIn or a similar profile:** \<https://www.linkedin.com/in/finn-cullen-a6a012346/>

Domain name change

---

js/sites.js

This PR changes updates my domain from [aarjavpatni.me](https://aarjavpatni.me) to [aarjav.xyz](https://aarjav.xyz)

Update Aarjav's domain

---

js/sites.js

**Full Name:** Mohan Dong
**Cohort Year:** 2030
**Full website URL:** https://www.powerium.io
**LinkedIn or a similar profile:** https://www.linkedin.com/in/powersagitar/

add `powerium.io` to webring

---

js/sites.js

Hi! My website domain has expired, therefore updating to the accessible link. Thank you!

Request to Update Website Link for Zona Hu

---

js/sites.js

I changed my website's URL a few months ago and forgot to change it here! 
Info:
Full name: Aurora Shi
Year: 2028
Website URL: https://aurorashi.com/

Fix Aurora's Website URL

---

js/sites.js

**Full Name:** Siddh Patel
**Full website URL:** https://www.siddhp.com/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/siddh-p/

Add Siddh Website

---

js/sites.js

**Full Name:** Julia Ilioukhina
**Full website URL:** https://juliailio.com
**LinkedIn or a similar profile:** https://www.linkedin.com/in/julia-ilioukhina/

Add Julia site

---

js/sites.js

**Full Name:** Alex Starosta
**Full website URL:** https://alexstarosta.dev
**LinkedIn or a similar profile:** https://www.linkedin.com/in/alexstarosta/

Add Alex's site

---

js/sites.js

**Full Name:** Rawsab Said
**Full website URL:**  https://rawsab.com/
_So we know you're human:_ hello
**LinkedIn or a similar profile:** https://www.linkedin.com/in/rawsabsaid/

Add rawsab.com to sites.js

---

js/sites.js

**Full Name:**  Sarah Yoo
**Cohort Year:** 2030
**Full website URL:** https://sarahyoo.vercel.app
**LinkedIn or a similar profile:**  https://www.linkedin.com/in/sarah-yoo-8bb083309/

add sarahyoo website

---

js/sites.js

**Full Name:** Justin Abuyuan
**Full website URL:** https://www.justin-abuyuan.xyz/
**LinkedIn or a similar profile:** https://www.linkedin.com/in/justin-abuyuan/

Add Justin Abuyuan

---

js/sites.js

**Full Name:**  Tobias Livadariu
**Cohort Year:**  2029
**Full website URL:** [https://www.tobias-livadariu.online/portfolio/](https://www.tobias-livadariu.online/portfolio/)
**LinkedIn or a similar profile:** [https://www.linkedin.com/in/tobias-livadariu/](https://www.linkedin.com/in/tobias-livadariu/)

Add tobias livadariu se29 to webring

---

js/sites.js

**Full Name:** Louie Yin
**Cohort Year:**  2029
**Full website URL:** https://www.louiefatooey.space/
_So we know you're human:_ Hi I'm Louie
**LinkedIn or a similar profile:** https://www.linkedin.com/in/louieyin/

Add Louie's Website

---

js/sites.js

Add Angelina Wang directly
